"use client";

import Link from "next/link";
import { ChevronLeft, ChevronRight, Copy, Eye, Pencil, Plus, X } from "lucide-react";
import { useState } from "react";
import { rupiah } from "@/lib/format";
import { AdminPagination } from "@/components/admin-pagination";
import type { AdminPagination as PaginationData } from "@/lib/admin-data";
import paginationStyles from "./admin-pagination.module.css";

type Voucher = { id: string; name: string; code: string; status: "ACTIVE" | "PAUSE" | "FINISH"; available: "public" | "private"; mode: "NOMINAL" | "PERCENTAGE"; discountValue: number; minPurchase: number | null; dailyLimit: number | null; totalLimit: number | null; userLimit: number | null; totalUsage: number; dailyUsage?: number; startAt: string | null; endAt: string | null; target: "TOTAL" | "PRODUCT_SUBTOTAL" | "SHIPPING"; usageCount: number };
function formatWibDateTime(value: string) { return new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(value)); }
function promoLabel(voucher: Voucher) { return voucher.mode === "PERCENTAGE" ? `${voucher.discountValue}%` : rupiah(voucher.discountValue); }
async function json(response: Response) { const text = await response.text(); try { return text ? JSON.parse(text) as Record<string, unknown> : {}; } catch { throw new Error("Respons server tidak valid"); } }

export function VoucherManager({ vouchers, pagination }: { vouchers: Voucher[]; pagination: PaginationData }) {
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [history, setHistory] = useState<{ voucher: { id: string; code: string; name: string }; usages: Array<{ id: string; discountAmount: number; createdAt: string; order: { publicNumber: string; guestName: string }; user: { name: string; email: string } }>; pagination: { page: number; pageSize: number; total: number; totalPages: number; hasPrevious: boolean; hasNext: boolean } } | null>(null);
  const [historyLoading, setHistoryLoading] = useState(false);
  async function duplicate(item: Voucher) { const code = window.prompt("Kode promo baru (akan dibuat PAUSE):", `${item.code}-COPY`)?.trim().toUpperCase(); if (!code) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/admin/vouchers/${item.id}/duplicate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); const result = await json(response); if (!response.ok) throw new Error(String(result.error || "Voucher gagal diduplikasi")); window.location.reload(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Voucher gagal diduplikasi"); setBusy(false); } }
  async function loadHistory(voucherId: string, voucherCode: string, voucherName: string, page = 1) { setHistoryLoading(true); setMessage(""); try { const response = await fetch(`/api/admin/vouchers/${voucherId}?page=${page}&pageSize=10`); const result = await json(response); if (!response.ok) throw new Error(String(result.error || "Riwayat tidak tersedia")); setHistory({ voucher: { id: voucherId, code: voucherCode, name: voucherName }, usages: (result.usages || []) as never, pagination: (result.pagination || { page: 1, pageSize: 10, total: 0, totalPages: 1, hasPrevious: false, hasNext: false }) as never }); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Riwayat tidak tersedia"); } finally { setHistoryLoading(false); } }
  return <div className="voucher-manager">
    <div className="admin-page-head"><div><p className="eyebrow">Operasional</p><h1>Voucher</h1><p>Atur kode promo, masa berlaku, kuota, dan lihat riwayat penggunaannya.</p></div><Link className="button button-dark" href="/admin/vouchers/new"><Plus size={16}/> Tambah voucher</Link></div>
    {message && <p className="form-banner error" role="alert">{message}</p>}
    <section className="table-card" aria-label="Daftar voucher"><div className="admin-table-wrap" role="region" aria-label="Daftar voucher" tabIndex={0}><table className="admin-table voucher-table"><thead><tr><th>Nama promo</th><th>Kode promo</th><th>Tampilan</th><th>Nilai diskon</th><th>Mode promo</th><th>Berlaku untuk</th><th>Kuota</th><th>Masa berlaku</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{vouchers.map(item => <tr key={item.id}><td className="admin-table-cell-wrap"><strong>{item.name}</strong></td><td><strong className="admin-data-code">{item.code}</strong></td><td><span className={`voucher-badge-tampilan ${item.available}`}>{item.available === "public" ? "Public" : "Private"}</span></td><td><strong className="admin-numeric">{promoLabel(item)}</strong>{item.minPurchase ? <span className="sub">Min {rupiah(item.minPurchase)}</span> : null}</td><td><span className={`voucher-badge-mode ${item.mode.toLowerCase()}`}>{item.mode === "PERCENTAGE" ? "Persentase" : "Nominal"}</span></td><td><span>{item.target === "TOTAL" ? "Total invoice" : item.target === "SHIPPING" ? "Ongkir" : "Subtotal produk"}</span></td><td><div className="voucher-stack-cell"><div><strong>{item.totalUsage} / {item.totalLimit ?? "UNL"}</strong> <span className="sub-label">Total</span></div><div><strong>{item.dailyUsage ?? 0} / {item.dailyLimit ?? "UNL"}</strong> <span className="sub-label">Harian</span></div><div><strong>{item.userLimit ? `Limit ${item.userLimit}` : "UNL"}</strong> <span className="sub-label">Per User</span></div></div></td><td>{!item.startAt && !item.endAt ? <span className="voucher-badge-unlimited">UNLIMITED</span> : <div className="voucher-stack-cell"><div><span className="sub-label">Start:</span> <span>{item.startAt ? formatWibDateTime(item.startAt) : "Sekarang"}</span></div><div><span className="sub-label">End:</span> <span>{item.endAt ? formatWibDateTime(item.endAt) : "Tanpa batas waktu"}</span></div></div>}</td><td><span className={`voucher-status ${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="table-actions"><Link className="icon-button" href={`/admin/vouchers/${item.id}`} aria-label={`Edit ${item.code}`} title="Edit"><Pencil size={15}/></Link><button className="icon-button" type="button" onClick={() => duplicate(item)} disabled={busy} aria-label={`Duplikat ${item.code}`} title="Duplikat"><Copy size={15}/></button><button className="icon-button" type="button" onClick={() => loadHistory(item.id, item.code, item.name, 1)} disabled={historyLoading} aria-label={`Lihat penggunaan ${item.code}`} title="Lihat penggunaan"><Eye size={16}/></button></div></td></tr>)}{!vouchers.length && <tr><td colSpan={10} className="table-empty-state">Belum ada voucher. Tambahkan voucher untuk mulai menawarkan promo.</td></tr>}</tbody></table></div></section>
    <AdminPagination data={pagination} basePath="/admin/vouchers" itemLabel="voucher" />
    {history && <div className="profile-modal-overlay" role="presentation"><section className="profile-modal-card voucher-history-modal"><div className="profile-modal-head"><div><h2>Riwayat Penggunaan Voucher</h2><p className="sub">Voucher: <strong>{history.voucher.code}</strong> · {history.voucher.name}</p></div><button className="icon-button" type="button" onClick={() => setHistory(null)} aria-label="Tutup riwayat"><X size={18}/></button></div><div className="profile-modal-body"><div className="admin-table-wrap" role="region" aria-label="Riwayat penggunaan voucher" tabIndex={0}><table className="admin-table"><thead><tr><th>No. Order & Pemesan</th><th>Akun Pengguna</th><th>Diskon</th><th>Waktu Transaksi</th></tr></thead><tbody>{history.usages.map(item => <tr key={item.id}><td><strong className="admin-data-code">{item.order.publicNumber}</strong><span className="sub">{item.order.guestName}</span></td><td><strong>{item.user.name}</strong><span className="sub">{item.user.email}</span></td><td><strong className="admin-numeric text-danger">-{rupiah(item.discountAmount)}</strong></td><td>{formatWibDateTime(item.createdAt)}</td></tr>)}{!history.usages.length && <tr><td colSpan={4} className="table-empty-state">Belum ada riwayat penggunaan untuk voucher ini.</td></tr>}</tbody></table></div>{history.pagination.total > 0 && <nav className={paginationStyles.root} style={{ borderTop: "1px solid var(--line)", marginTop: "16px" }} aria-label="Paginasi riwayat penggunaan"><p className={paginationStyles.summary}>Menampilkan <strong>{Math.min(history.pagination.total, (history.pagination.page - 1) * history.pagination.pageSize + 1)}–{Math.min(history.pagination.total, history.pagination.page * history.pagination.pageSize)}</strong> dari <strong>{history.pagination.total}</strong> riwayat</p><div className={paginationStyles.controls}>{history.pagination.hasPrevious ? <button className={paginationStyles.link} type="button" disabled={historyLoading} onClick={() => loadHistory(history.voucher.id, history.voucher.code, history.voucher.name, history.pagination.page - 1)}><ChevronLeft size={14}/> Sebelumnya</button> : <span className={paginationStyles.disabled}>Sebelumnya</span>}<span className={paginationStyles.pageLabel}>Halaman {history.pagination.page} / {history.pagination.totalPages}</span>{history.pagination.hasNext ? <button className={paginationStyles.link} type="button" disabled={historyLoading} onClick={() => loadHistory(history.voucher.id, history.voucher.code, history.voucher.name, history.pagination.page + 1)}>Berikutnya <ChevronRight size={14}/></button> : <span className={paginationStyles.disabled}>Berikutnya</span>}</div></nav>}</div></section></div>}
  </div>;
}
